# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-17 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Area')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Evidence')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('weekday', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('theoretical_hours', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('units', models.IntegerField()),
                ('areas', models.ManyToManyField(to='schedule.Area')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.SchoolSubject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('no_employee', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('career', models.CharField(max_length=250)),
                ('level_of_study', models.CharField(max_length=250)),
                ('speciality', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='schoolsubjectlog',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher'),
        ),
        migrations.AddField(
            model_name='career',
            name='school_subjects',
            field=models.ManyToManyField(to='schedule.SchoolSubject'),
        ),
    ]
